vantage-sh/docs.vantage.sh

docs/enabling_gcp_billing_export.md
mkdocs.yml

Bringing the information from our beta google doc into docs.vantage.sh
https://docs.google.com/document/d/1835SiIWSV8j8gwM3Gp5y4lI-7ROO3zouNa_y7S8bjcU/edit#

feat: GCP Billing Export docs.

---

docs/microsoft_teams_integration.md
docs/reports.md
docs/slack_integration.md
mkdocs.yml

docs for slack, teams, + some updates for general report notifications

---

docs/connecting_aws.md

@EverettBerry feel free to merge in if this looks good to you.

AWS Cost and Usage Report Delay Explanation

---

docs/connecting_snowflake.md

Generally referred to as `allowed list` in their docs https://docs.snowflake.com/en/user-guide/network-policies

Use allowed list over whitelist.

---

docs/autopilot.md
docs/cost_reports.md
docs/segments.md

Update pages for 3 CS tickets:
- Add note regarding AISPL customers for Autopilot
- Rewrite Amortization section to explain Vantage amortization logic; link to relevant blog
- Add note to Segments about contacting Support to enable feature

Updates for CS tickets

---

docs/connecting_aws.md

Adding instructions regarding options for a backfilled/historical CUR for reingestion into Vantage.

Add instructions to create a backfilled CUR

---

docs/security.md

- Addresses #46
- Also add page front matter
- Fix typos
- Restructure FAQs into details blocks

Fix links in security.md and update page format

---

docs/connecting_aws.md
docs/vantage_account.md

- Rework Account Settings page to explain organization and personal settings
- Move one section to the connecting AWS page where it makes more sense

Update Account page -- part of onboarding page updates

---

docs/kubernetes_agent.md

Did the same update in the helm chart after more investigation and is a bit easier to communicate:
https://github.com/vantage-sh/helm-charts/blob/main/charts/vantage-kubernetes-agent/values.yaml#L32-L37

Simplify resource estimates.

---

docs/kubernetes_agent.md
docs/opencost.md
docs/terraform.md
docs/vql.md

- Remove old early access notes
- beta > Early Access

Remove old notes

---

docs/rbac.md
sidebars.js

@whereandy -- Round 2 -- let me know if you run into issues spinning this up locally.

Updates for RBAC

---

docs/executive_reporting.md
docs/hidden_costs.md
docs/team_accountability.md
docs/workspaces.md

Edits to the user workflow pages since they are linked from the quickstart. Edits to the Workspaces page update for currency.

User workflow edits

---

docs/kubernetes_agent.md

This will probably be a relatively common error. Not sure how we want this organized but figured this was a good way to get the details documented and then leave it up to the team to move it as desired.

Add documentation for nodeAddressTypes.

---

docs/connecting_databricks.md

As advertised, added new section to match updates in console.

Add new CLI setup section for Databricks

---

README.md

Update README for Contributions

---

docs/kubernetes_agent.md

Update k8s with additional prereq

---

docusaurus.config.js

Added company items, like privacy policy, to footer. Touched base with Trevor on this.

Reorg Footer

---

docs/kubernetes_agent.md

Im hesitant to try to document the deleting PVC/PV/Pod steps as they would vary quite a bit based on customer naming scheme and some aspects being randomly generated. Uninstall via helm + reinstall is the more straightforward approach.

Add docs for EOF errors when starting.

---

docs/kubernetes_agent.md

The feature is still WIP but wanted to start documentation.

Document S3 persistence for the agent.

---

docs/data_dictionary.md
docs/vql.md

Add `costs.charge_type` to VQL examples and Data Dictionary for all providers.

Add charge type to vql and data dictionary

---

docs/connecting_aws.md

Add GovCloud note and some format fixes

---

docs/kubernetes_agent.md

@macb not sure if there was much else to say here, but tagging you for a review. Thanks!

Add K8s manifest based option

---

docs/sso.md
docs/terraform.md

Added some updates to Terraform docs to be current.

Update Terraform docs

---

docs/kubernetes_agent.md

@macb Not sure if there is anything else to add here. It's just a reference to the errors in the docs for searchability. If there's any other AKS-specific items, we can add them here.

Add AKS-specific section

---

docs/cost_reports.md
docs/dashboards.md
docs/saved_filters.md

Will add in the GIF we use for the release announcement.

Add saved filters on dashboards

---

docs/kubernetes_agent.md

Add section to upgrade agent. Showed preview to team via slack.

Add upgrade section

---

docs/cost_reports.md
docs/financial_commitment_reports.md

* Add new section to cost reports
* Reference on FCR page

Add charge type table for grouping category on cost reports

---

docs/active_resources.md
docs/connecting_aws.md

Clarify note to better describe limitations and alternatives.

Clarify note about GovCloud active resources

---

docs/changelog.md
docs/dashboards.md

Includes first half changes. Waiting to merge with any K8s changes.

Add first half changelog

---

docs/per_unit_costs.md

- Add new section to per unit costs page
- Need to confirm code samples

Add docs for business metrics api

---

docs/cost_reports.md

Adds instructions for using the custom date picker.

Custom Date Comparison 

---

docs/cost_reports.md

Reverts vantage-sh/docs.vantage.sh#133

Revert "Custom Date Comparison "

---

docs/cost_reports.md

Reverted last PR as it didn't look like this was in prod quite yet. Adds instructions for custom dates.

Add custom date instructions

---

docs/terraform.md

Updated for future-proofing purposes. Removed the tables and specific links for each resource and data source for maintainability. Removed "future primitive" section as a lot of this is currently being addressed. Added some reference links.

Update Terraform page

---

docs/connecting_snowflake.md

Add troubleshooting steps for query error.

Add detailed troubleshooting steps for Snowflake

---

docs/changelog.md

Add new endpoints

---

docs/connecting_mongodb-atlas.md
docs/data_dictionary.md

Tags are now supported for Mongo. Updated integration page and data dictionary accordingly.

Add tags for MongoDB

---

docs/connecting_aws.md
docs/connecting_azure.md
docs/connecting_confluent.md
docs/connecting_coralogix.md
docs/connecting_databricks.md
docs/connecting_datadog.md
docs/connecting_fastly.md
docs/connecting_gcp.md
docs/connecting_kubernetes.md
docs/connecting_mongodb-atlas.md
docs/connecting_new_relic.md
docs/connecting_open_ai.md
docs/connecting_oracle.md
docs/connecting_planetscale.md
docs/connecting_snowflake.md
docs/rbac.md
docs/workspaces.md

- Add page clarity and reorganize page
- Move instructions up on page for each integration
- Rewrite use cases and simplify language

Workspaces update

---

docs/connecting_kubernetes.md
docs/kubernetes.md

Made updates only to efficiency reports page

K8s GPU Release

---

docs/changelog.md

Remaining updates for May

---

docs/connecting_aws.md

https://aws.amazon.com/blogs/aws-cloud-financial-management/introducing-data-exports-for-billing-and-cost-management/

CUR created by Vantage is now a Data Export

---

docs/vql.md

Add new example for multiple values on one tag

Add additional VQL example

---

docs/connecting_aws.md
docs/connecting_azure.md
docs/connecting_confluent.md
docs/connecting_coralogix.md
docs/connecting_databricks.md
docs/connecting_datadog.md
docs/connecting_fastly.md
docs/connecting_gcp.md
docs/connecting_kubernetes.md
docs/connecting_mongodb-atlas.md
docs/connecting_new_relic.md
docs/connecting_oracle.md
docs/connecting_planetscale.md
docs/connecting_snowflake.md

Add reporting dimensions updates

---

docs/changelog.md

August Changelog

---

docs/kubernetes.md

I believe this is all that needs to be updated on here - https://docs.vantage.sh/kubernetes. Will hold on publishing until Monday or whenever the update goes out.

K8s minutely

---

docs/terraform.md

Add terraform import docs

---

docs/rbac.md

Added updates to two sections on RBAC docs

Add Integration Owner role

---

docs/connecting_aws.md
docs/connecting_azure.md
docs/connecting_confluent.md
docs/connecting_coralogix.md
docs/connecting_databricks.md
docs/connecting_datadog.md
docs/connecting_fastly.md
docs/connecting_gcp.md
docs/connecting_github.md
docs/connecting_kubernetes.md
docs/connecting_mongodb-atlas.md
docs/connecting_new_relic.md
docs/connecting_oracle.md
docs/connecting_planetscale.md
docs/connecting_snowflake.md
docs/provider_data_refresh.md
sidebars.js

Based on request for table of info

Add docs for data refresh

---

docs/kubernetes_agent.md
docs/security.md

Add additional error troubleshooting to K8s docs

---

docs/partners.md

Add updated docs for MSP RBAC table

Add new MSP RBAC table

---

docs/kubernetes_agent.md

Add 404 not found error and cluster naming guidance

---

docs/vql.md
docs/vql_financial_commitment_report.md
docs/vql_network_flow_report.md
sidebars.js

Add new VQL docs

---

docs/connecting_azure.md

Add azure mca steps
